/* Temporada 1 · Capítulo 1 · PARTE B · Acto 2: «La vida en la secta»
   Se carga DESPUÉS de cap01_a.js. Amplía el 'patio' con nuevas opciones y eventos. */
Object.assign(TECNICAS,{rasca:{n:'Palma del Dragón que se Rasca',c:4,d:[8,24],s:'su'}});
const P0=SC.patio.c;
registrarCapitulo({temporada:1,n:1,parte:'B',titulo:'El Reclutamiento',escenas:{
 patio:{...SC.patio,c:[...P0.slice(0,-2),
  {x:'Comedor de la secta, con Madre Lin · 1 h',to:'comedor',fx:{t:1}},
  {x:'Dormitorio de aspirantes · 1 h',to:'dormitorio',fx:{t:1}},
  {x:'Clase de Qi del Anciano Mo · 2 h',to:'clase',fx:{t:2}},
  {x:'Tablón de misiones',to:'tablon'},
  {x:'Practicar con el Abuelo Pei (técnica secreta)',to:'pei_leccion',req:{no:'peiLeccion'},oc:1},
  {x:'«¡Te reto, novato!» · Wang te espera en el patio',to:'wang_reto',req:{dia:3,no:'wangDuelo'},oc:1},
  {x:'El Maestro del Horno te hace señas con urgencia',to:'horno_queja',req:{dia:3,no:'hornoQueja'},oc:1},
  ...P0.slice(-2)]},
 comedor:{h:'El Comedor',t:['Madre Lin, ancha como una puerta y con un cucharón que impone respeto, remueve una olla del tamaño de un estanque. «¡Flacos, a comer! Aquí no se cultiva con el estómago vacío ni con la lengua ociosa!»','«Sopa de cinco sabores —susurra el Abuelo Pei—. Cuatro de ellos son mentira.»'],
  c:[{x:'Pedir un cuenco de sopa (5 monedas · +30 Vida, +5 Qi) · 1 h',to:'comedor',req:{oro:5},fx:{oro:-5,hp:30,qi:5,t:1}},
     {x:'Preguntarle a Madre Lin por los chismes de la secta',to:'lin_rumores',req:{no:'rumor'},oc:1},
     {x:'Volver al patio',to:'patio'}]},
 lin_rumores:{t:['Madre Lin se inclina y baja la voz hasta un tono casi discreto. «Las hierbas del Horno llevan días desapareciendo. Dicen que son los monos. Yo digo que los monos no saben abrir cerrojos. Y menos con llave.»','Se endereza y blande el cucharón. «Pero yo no he dicho nada. Y si lo he dicho, es mentira. Come.»'],fx:{fl:{rumor:true},xp:5},c:[{x:'Volver al comedor',to:'comedor'}]},
 dormitorio:{h:'El Dormitorio',t:['Gordo Tao, tu compañero de litera, está despatarrado sobre su cama con una bolsa de dulces en el pecho. A su lado, Lian, una joven de mirada seria, repasa un pergamino con la postura de quien nunca ha bostezado.','«Aquí tienes a la sabiduría y a la glotonería —resume el Abuelo Pei—. Yo, desde luego, me quedo con la glotonería.»'],
  c:[{x:'Hablar con Gordo Tao',to:'tao'},{x:'Hablar con Lian',to:'lian'},{x:'Volver al patio',to:'patio'}]},
 tao:{t:['«¡Eh, vecino! —dice Tao con la boca llena—. Dicen que las cartas dan suerte. Yo digo que la suerte da cartas. Y yo tengo ambas. ¿Una partidita rápida? Prometo no hacer trampas. Mucho.»'],
  c:[{x:'Apostar 10 monedas a las cartas (prueba de Suerte)',chk:{s:'su',dc:9,ok:'tao_gana',ko:'tao_pierde'},req:{oro:10,no:'taoApuesta'},oc:1,fx:{fl:{taoApuesta:true}}},
     {x:'Volver al dormitorio',to:'dormitorio'}]},
 tao_gana:{t:['Tao mira sus cartas, luego las tuyas, luego al techo. «No es posible. Debo de estar hechizado. O tú. O la baraja.» Te paga con un suspiro dramático.'],fx:{oro:30},c:[{x:'Volver al dormitorio',to:'dormitorio'}]},
 tao_pierde:{t:['Tao despliega una escalera de color tan perfecta que casi resulta sospechosa. «¡Qué suerte! —exclama—. Qué pena para ti. Qué buena para mí.»'],fx:{oro:-10},c:[{x:'Volver al dormitorio',to:'dormitorio'}]},
 lian:{t:['Lian levanta la vista. «Respiras demasiado fuerte. Se nota que estás nervioso, y eso es un error. El Qi se asusta del ruido.»','Hace una pausa. «Si quieres, te enseño a respirar. Es gratis. No me debes nada. Salvo silencio.»'],
  c:[{x:'Aceptar su consejo de respiración',to:'dormitorio',req:{no:'lianConsejo'},oc:1,fx:{xp:15,fl:{lianConsejo:true}}},{x:'Volver al dormitorio',to:'dormitorio'}]},
 clase:{h:'Clase de Qi',t:['El Anciano Mo recorre el aula con las manos a la espalda y una expresión de profundo aburrimiento sabio. «Hoy hablaremos del Qi. Del Qi y de lo poco que comprendéis de él.»','Se detiene frente a ti. «Tú. Dime: ¿qué es el aliento del cielo?»'],
  c:[{x:'Responder con calma (prueba de Espíritu)',chk:{s:'es',dc:10,ok:'clase_ok',ko:'clase_ko'},req:{no:'claseQi'},oc:1,fx:{fl:{claseQi:true}}},{x:'Escuchar sin hablar y volver al patio',to:'patio'}]},
 clase_ok:{t:['Tu respuesta sale con una serenidad que no sabías que tenías. El Anciano Mo arquea una ceja, que es lo más parecido a un elogio que ha hecho en treinta años.','«Aceptable. Siéntate. Y no te lo creas.»'],fx:{xp:25,mqi:3},c:[{x:'Volver al patio',to:'patio'}]},
 clase_ko:{t:['Abres la boca y lo que sale es un ruido entre la tos y la filosofía. El Anciano Mo suspira. «Eso, joven aspirante, es lo que llamamos un malentendido cósmico.» Toda la clase ríe, salvo Lian.'],c:[{x:'Volver al patio, humillado',to:'patio'}]},
 tablon:{h:'Tablón de misiones',t:['Un tablón de madera lleno de pergaminos clavados con chinchetas y desesperación. Casi todos piden «voluntarios». Casi ninguno paga.'],
  c:[{x:'Limpiar la fragua del maestro Tie · 2 h',to:'fragua',req:{no:'fragua'},oc:1,fx:{t:2}},{x:'Volver al patio',to:'patio'}]},
 fragua:{t:['Tie te entrega un cubo, un trapo y una mirada de «no preguntes». Tras dos horas de hollín, descubres que la fragua llevaba años sin limpiarse y que algo en un rincón ya tenía vida propia.','«Bien —dice Tie, mirándote—. Si no te ha devorado, tienes futuro.»'],fx:{oro:25,item:'mineral_hierro',fl:{fragua:true}},c:[{x:'Volver al patio',to:'patio'}]},
 wang_reto:{h:'El reto de Wang',t:['Wang te espera en medio del patio, rodeado de un coro de admiradores y con el cabello tan engominado que refleja el sol. «¡Novato! Tu insolencia en la cola me ha quitado el sueño. Te reto a un duelo amistoso. Sin armas letales. Solo… dolor.»','«Qué amable —murmura el Abuelo Pei—. Dolor bajo palabra de honor.»'],
  c:[{x:'Aceptar el duelo',to:'duelo_wang'},{x:'Rechazarlo, por ahora',to:'patio'}]},
 duelo_wang:{t:['Wang adopta su pose más teatral. Una de las admiradoras suelta un suspiro ensayado. Con un gesto exagerado, se desenvaina un abanico en lugar de una espada.','«¡Prepárate a conocer la Danza del Abanico de las Mil Brisas!»'],f:{e:'wang',win:'wang_gana',lose:'wang_pierde',flee:'patio'}},
 wang_gana:{t:['Wang cae sentado con el abanico roto sobre el regazo. «¡Esto… esto es un accidente! ¡Una trampa del destino!» Sus admiradores se dispersan con prisa discreta.','«Y así —sentencia el Abuelo Pei— se escribe la historia: con abanicos rotos.»'],fx:{oro:40,item:'pildora_salud',fl:{wangDuelo:true,wangVencido:true}},c:[{x:'Volver al patio',to:'patio'}]},
 wang_pierde:{t:['Caes de rodillas, con la visión borrosa. Wang se sacude el polvo con una elegancia exagerada. «Qué débil. Qué pena. Y qué barato», dice, mientras te quita 20 monedas «como compensación por el espectáculo».','El Abuelo Pei suspira: «Esto lo vamos a recordar. Lo vamos a recordar mucho.»'],fx:{hp:20,oro:-20,fl:{wangDuelo:true,wangGano:true}},c:[{x:'Volver al patio, con orgullo magullado',to:'patio'}]},
 horno_queja:{h:'El Maestro del Horno',t:['El Maestro Hu, un hombre flaco con barba chamuscada y ojeras de alquimista, te agarra del brazo. «¡Joven! Esta semana han desaparecido tres cestas de hierbas del almacén. ¡Tres! Y la cerradura estaba intacta.»','«Alguien con llave —murmura el Abuelo Pei—. O alguien con muy buena mano.»','Hu baja la voz. «Si te enteras de algo, ven a verme. Y si eres tú, también. Pero entonces con disculpas.»'],
  fx:{fl:{hornoQueja:true,investigas:true},xp:10},c:[{x:'Prometer que abrirás los ojos',to:'patio'}]},
 pei_leccion:{h:'La técnica secreta del Abuelo Pei',t:['«Vamos a practicar —anuncia el Abuelo Pei, con una voz grave de maestro—. Te enseñaré la Palma del Dragón que se Rasca. Es una técnica ancestral, devastadora… e impredecible.»','Te explica el movimiento: una palma extendida, un giro de muñeca y un rasguño al aire con elegancia absurda. A veces destroza una roca; a veces, un pelo suelto.'],
  fx:{tc:'rasca',fl:{peiLeccion:true},xp:10},c:[{x:'Volver al patio, con técnica nueva',to:'patio'}]}
}});
