/* Temporada 1 · Capítulo 1 · Primavera: «El Reclutamiento» (versión base para probar el motor) */
const pelea=(e,win,flee,t)=>({t:[t],f:{e,win,lose:'muerte',flee}});
registrarCapitulo({temporada:1,n:1,titulo:'El Reclutamiento',escenas:{
 inicio:{h:'Capítulo 1 · El Reclutamiento',cp:1,t:['Despiertas en tu cabaña con una grieta en el techo y otra en la dignidad. Hoy la Secta del Dragón Azur recluta aspirantes.','Tu espada de bambú, apoyada en la pared, carraspea. «¡Por fin! Cuarenta años aquí dentro. ¿Tienes algo de comer? Soy el Abuelo Pei, antiguo Líder Supremo, o algo parecido.»'],
  c:[{x:'Coger la espada (y a su inquilino) e ir al pueblo · 1 h',to:'pueblo',fx:{item:'espada_madera',t:1}}]},
 pueblo:{t:['En un callejón, un matón bloquea el paso. «Peaje, campesino.»','«Cobra por respirar —susurra el Abuelo Pei—. Dale una lección, yo te grito consejos inútiles.»'],
  c:[{x:'Pelear con el matón',to:'f_maton',fx:{t:1}},{x:'Volver a casa',to:'inicio'}]},
 f_maton:pelea('maton','entrada','pueblo','El matón se arremanga con teatralidad.'),
 entrada:{h:'La puerta del Dragón Azur',cp:1,t:['El Anciano de la puerta te mira de arriba abajo y asiente con un suspiro de funcionario. «Aceptado como Discípulo Iniciado.»','Un maestro te ofrece una meditación guiada de bienvenida. Huele a incienso y a presupuesto.'],
  c:[{x:'Aceptar la meditación · +20 XP · 2 h',to:'patio',fx:{xp:20,oro:30,t:2}}]},
 patio:{h:'Patio Central',cp:1,t:['El patio de la secta huele a tinta, a sopa y a ambición. Los caminos se abren ante ti.'],
  c:[{x:'Jardines Exteriores (caza fácil) · 2 h',to:'jardines',fx:{t:2}},
     {x:'Bosque de Bambú (caza peligrosa) · 3 h',to:'bosque',fx:{t:3}},
     {x:'Pabellón del Conocimiento (acertijo) · 1 h',to:'pabellon',fx:{t:1}},
     {x:'Barracones (socializar) · 1 h',to:'barracones',fx:{t:1}},
     {x:'Mercado de Gong Gong',to:'mercado'},{x:'Herrería del maestro Tie',to:'herreria'},{x:'Horno de Alquimia',to:'horno'},
     {x:'Dormir en tus aposentos · 8 h (recuperación total)',to:'patio',fx:{t:8,dormir:1}},
     {x:'Presentarte al examen de fin de trimestre (desde el día 6)',to:'examen',req:{dia:6}}]},
 mercado:{h:'Mercado',t:['Gong Gong, mercader sin vergüenza, agita un abanico. «¡Compre dos y pague tres, que es más emocionante!»'],shop:'botica',back:'patio'},
 herreria:{h:'Herrería',t:['El maestro Tie golpea el yunque con ritmo de gong. «¿Armas? ¿Armaduras? ¿Un martillo emocional?»'],forja:1,back:'patio'},
 horno:{h:'Horno de Alquimia',t:['El gran horno ruge. Un cartel dice: «No tocar. No olfatear. No llorar».'],alq:1,back:'patio'},
 jardines:{t:['Los jardines son seguros, salvo por las plagas con ambiciones empresariales.'],
  c:[{x:'Atacar a una Rata Busca-Tesoros',to:'f_rata'},{x:'Atacar a un Mono Ladrón',to:'f_mono'},{x:'Volver al patio',to:'patio'}]},
 f_rata:pelea('rata','jardines','jardines','La rata te mira como quien ya ha visto tu bolsa.'),
 f_mono:pelea('mono','jardines','jardines','El mono mastica una píldora que, sospechosamente, era tuya.'),
 bosque:{t:['El bosque de bambú cruje. Algo con ojos rojos te observa; algo con mala educación, también.'],
  c:[{x:'Enfrentar al Lobo de Ojos Rojos',to:'f_lobo'},{x:'Buscar al Bandido del Camino',to:'f_bandido'},{x:'Volver al patio',to:'patio'}]},
 f_lobo:pelea('lobo','bosque','bosque','El lobo aúlla. Por la forma, parece una queja.'),
 f_bandido:pelea('bandido','bosque','bosque','El bandido se presenta: «Buenas tardes, vengo a robarle. Disculpe las molestias.»'),
 pabellon:{t:['El Maestro Sabio acaricia su barba. «Soy ligero como una pluma, pero ni el gigante más fuerte puede sostenerme mucho tiempo. ¿Qué soy?»'],
  c:[{x:'«El aliento»',to:'acertijo_ok',req:{no:'acertijo'},oc:1,fx:{item:{tunica_seda:1,medalla:1},fl:{acertijo:true},xp:15}},
     {x:'«El agua»',to:'acertijo_ko',req:{no:'acertijo'},oc:1},{x:'«La sombra»',to:'acertijo_ko',req:{no:'acertijo'},oc:1},
     {x:'Volver al patio',to:'patio'}]},
 acertijo_ok:{t:['El Maestro sonríe. «Excelente mente. Toma esta túnica y esta medalla.» El Abuelo Pei murmura: «Yo también lo sabía, solo que estaba dormido.»'],c:[{x:'Volver al patio',to:'patio'}]},
 acertijo_ko:{t:['«Tu mente aún está nublada», suspira el Maestro. Lo sientes como una bofetada cortés.'],c:[{x:'Volver al patio',to:'patio'}]},
 barracones:{t:['Wang, discípulo mayor y arrogante, te intercepta. «¡Novato! Dame tus monedas o te enseñaré respeto.»'],
  c:[{x:'Darle 10 monedas',to:'patio',req:{oro:10},fx:{oro:-10}},
     {x:'Desenvainar y negarte',to:'f_wang',req:{no:'wang'},oc:1},
     {x:'Huir con dignidad (poca)',to:'patio'}]},
 f_wang:{t:['Wang adopta una pose heroica. Se le cae una horquilla.'],f:{e:'wang',win:'wang_ok',lose:'muerte',flee:'patio'}},
 wang_ok:{t:['Wang escupe aire y jura venganza con voz de gallo. Le registras los bolsillos, con elegancia.'],fx:{fl:{wang:true}},c:[{x:'Volver al patio',to:'patio'}]},
 examen:{h:'Examen de trimestre',cp:1,t:['Tres ancianos te examinan sobre Qi, filosofía y la manera correcta de servir té.'],
  c:[{x:'Concentrarte (prueba de Mente)',chk:{s:'me',dc:11,ok:'fin1',ko:'examen_ko',fxko:{hp:-10}}}]},
 examen_ko:{t:['Suspendes por derramar el té. Puedes volver a intentarlo cuando quieras.'],c:[{x:'Volver al patio',to:'patio'}]},
 fin1:{h:'Fin del Capítulo 1',t:['Apruebas. Ascendes a Discípulo Común. El Capítulo 2 comenzará con hierbas que desaparecen del Horno.'],fx:{rango:1,oro:100},end:'Capítulo 1 completado'},
 muerte:{h:'Fin del camino',t:['Caes. El Abuelo Pei suspira: «Qué mal timing.»'],end:'Muerte en la secta'}
}});
