/* Temporada 1 · Capítulo 1 · PARTE C · Acto 3: «La noche de las hierbas y el examen del corazón»
   Se carga DESPUÉS de cap01_b.js. Sustituye 'examen' y 'fin1' y añade la investigación. */
Object.assign(ENEMIGOS,{
 encapuchado:{n:'Figura Encapuchada',hp:90,a:14,xp:60,o:50,l:{jade_azul:1,flor_loto_lunar:.5}},
 instructor:{n:'Instructor Xu (duelo de examen)',hp:85,a:11,xp:40,o:0,l:{}}});
OBJ.ficha_tigre={n:'Ficha de Jade Negro',tipo:'clave',pr:0,d:'Marcada con una garra de tigre. Fría como una promesa rota.'};
const P1=SC.patio.c;
registrarCapitulo({temporada:1,n:1,parte:'C',titulo:'El Reclutamiento',escenas:{
 patio:{...SC.patio,c:[...P1.slice(0,-2),
  {x:'Investigar el almacén de hierbas desaparecidas · 1 h',to:'almacen',req:{fl:'investigas',no:'invFin'},oc:1,fx:{t:1}},
  ...P1.slice(-2)]},
 almacen:{h:'El Almacén de Hierbas',t:['El almacén huele a tierra mojada y a promesas de curación. Los estantes, antes llenos, muestran ahora huecos del tamaño de cestas. La cerradura está intacta: ni un arañazo, ni una marca.','Sobre el pestillo hay un hilo de seda roja, casi invisible. «Quien robó esto tenía llave —murmura el Abuelo Pei—. O era un fantasma. Y yo ya conozco a uno.»'],
  c:[{x:'Salir a buscar huellas al amanecer · 2 h',to:'huellas',fx:{t:2}}]},
 huellas:{h:'Huellas en el barro',t:['En el barro del jardín, detrás del almacén, hay huellas de sandalias con una marca curiosa en la suela: una garra de tres dedos. Y entre las huellas, migas de hojas secas que forman un rastro hacia el norte.'],
  c:[{x:'Seguir el rastro con paciencia (prueba de Suerte)',chk:{s:'su',dc:9,ok:'testigo',ko:'testigo',fxok:{xp:10},fxko:{hp:-5}}}]},
 testigo:{t:['Al volver al dormitorio, Gordo Tao se sobresalta, esconde una bolsa de dulces bajo la almohada y confiesa a la primera. «Esa noche salí a por un bocado. Solo uno. Bueno, siete. Y vi a alguien encapuchado con una linterna de fuego verde, junto a la Muralla Norte.»','«¿Y qué hiciste?», preguntas. «Me escondí dentro de un barril —responde con dignidad—. Es mi mejor técnica de combate.»'],
  c:[{x:'Esperar esa noche en la Muralla Norte · 4 h',to:'muro',fx:{t:4}}]},
 muro:{h:'La Muralla Norte',cp:1,t:['La luna es una uña de plata. Entre las sombras, una figura encapuchada avanza con una cesta en cada brazo y una linterna de llama verde que no proyecta luz, sino ausencia.','Se detiene junto a la pared del acantilado y susurra algo. La roca, que no debería escuchar, parece escuchar.'],
  c:[{x:'Atacar por sorpresa',to:'f_encap'},{x:'Seguirlo en silencio (prueba de Suerte)',chk:{s:'su',dc:10,ok:'rastro',ko:'f_encap'}}]},
 f_encap:{t:['Pisas una rama. Es la rama más ruidosa de la historia. La figura se gira despacio. La llama verde se alarga como una lengua. «Mala hora para pasear, aspirante», dice una voz que parece de varios.'],f:{e:'encapuchado',win:'encap_gana',lose:'encap_huye',flee:'rastro'}},
 encap_gana:{t:['La figura retrocede con una risa sin humor. «Interesante. Muy interesante.» Al desvanecerse en la niebla, deja caer una pequeña ficha de jade negro marcada con una garra de tigre.','El Abuelo Pei, por primera vez, no hace ningún chiste.'],fx:{item:'ficha_tigre',fl:{token:true}},c:[{x:'Seguir su rastro hasta el acantilado',to:'rastro'}]},
 encap_huye:{t:['Caes de rodillas. La llama verde te roza la frente y todo se vuelve silencio. Al despertar, Lian está inclinada sobre ti con el ceño fruncido. «Eres un imprudente.»','En tu pecho, prendida como una burla, hay una ficha de jade negro con una garra de tigre. «Un recuerdo», dice una nota. Nada más.'],fx:{hp:30,item:'ficha_tigre',fl:{token:true}},c:[{x:'Ir al acantilado con Lian',to:'rastro'}]},
 rastro:{h:'La puerta bajo el Dragón',t:['Al amanecer, el rastro de migas termina en una pared de roca en la que, entre la niebla, se adivina una puerta de jade sellada con un dragón azul de ojos cerrados. De la piedra sale un zumbido grave, como un corazón enorme que late despacio.','«Yo conozco este sello —susurra el Abuelo Pei, con una voz que no reconoces—. Lo conozco. Y no debería estar abierto.»'],fx:{fl:{rastro:true},xp:20},c:[{x:'Volver para informar a los maestros · 2 h',to:'informe',fx:{t:2}}]},
 informe:{t:['El Maestro Hu y el Anciano Mo te escuchan en silencio. Al ver la ficha de jade negro, el Anciano Mo se queda blanco como el papel. Cierra la mano sobre ella.','«Te agradezco lo que has hecho, joven. Y te pido una cosa: ni una palabra hasta después del examen. Hay cosas en esta montaña que despiertan si se pronuncian.»'],fx:{fl:{invFin:true},oro:50,xp:30},c:[{x:'Asentir y volver al patio',to:'patio'}]},
 examen:{h:'El Examen del Trimestre',cp:1,t:['El Gran Salón del Dragón Azur huele a incienso y a nervios. Tres ancianos, sentados bajo un dragón de jade, os examinan uno a uno. En la fila, Lian respira como quien reza; Tao se muerde las uñas, o los dulces.','Wang, de brazos cruzados, te lanza una sonrisa de gato satisfecho.','«Tranquilo —murmura el Abuelo Pei—. Yo también sudaba. Con la diferencia de que yo no tenía pulso.»'],
  c:[{x:'Comenzar la prueba teórica',to:'examen_teoria'}]},
 examen_teoria:{t:['El primer examen es escrito: tres preguntas sobre el flujo del Qi, la respiración y una cuarta, inesperada, sobre la manera correcta de despedirse de un maestro.'],
  c:[{x:'Responder con calma (prueba de Mente)',chk:{s:'me',dc:10,ok:'examen_practica',ko:'examen_ko',fxok:{xp:15},fxko:{hp:-10}}}]},
 examen_practica:{t:['La segunda prueba es práctica. El Instructor Xu, un hombre de espalda ancha y mirada paciente, se coloca frente a ti. «No es para vencer —dice—. Es para mostrar quién eres cuando te golpean.»','«No lo mates —susurra el Abuelo Pei—. Es de tu secta. Aunque ya se sabe que las sectas son flexibles.»'],f:{e:'instructor',win:'examen_corazon',lose:'examen_corazon',flee:'examen_corazon'}},
 examen_corazon:{h:'La pregunta del corazón',t:['Los tres ancianos se levantan. El Anciano Mo avanza hacia ti. La sala queda en silencio; hasta la llama de los incensarios parece contener el aliento.','«La última prueba no tiene respuesta correcta, joven aspirante. Solo respuesta verdadera. —Hace una pausa—. ¿Por qué quieres cultivar?»'],fx:{hp:30},
  c:[{x:'«Para proteger a quienes no pueden protegerse.»',to:'resp_honor',fx:{fl:{viaHonor:true},st:{es:1}}},
     {x:'«Para comprender. Y no dejar que nadie decida por mí qué debo creer.»',to:'resp_astucia',fx:{fl:{viaAstucia:true},st:{me:1}}},
     {x:'«Para ser tan fuerte que nunca vuelvan a empujarme.»',to:'resp_poder',fx:{fl:{viaPoder:true},st:{cu:1}}}]},
 resp_honor:{t:['Piensas en tu aldea, en el huerto de nabos, en la gente que te dio de comer cuando no tenías nada. El Anciano Mo te mira un largo rato. «Es el camino de quienes cargan con otros —dice con voz suave—. Es el más pesado. Y el más hermoso.»','Algo en el pecho del Abuelo Pei vibra, como una cuerda tensa.'],c:[{x:'Esperar el veredicto',to:'veredicto'}]},
 resp_astucia:{t:['Las palabras te salen más claras de lo que esperabas. En la sala hay un murmullo; Wang frunce el ceño, pero uno de los ancianos oculta una sonrisa. «Un camino peligroso —observa el Anciano Mo—. Quien lo recorre aprende demasiado pronto que casi todo es un cuento. Pero también aprende cuáles merece la pena creer.»'],c:[{x:'Esperar el veredicto',to:'veredicto'}]},
 resp_poder:{t:['Lo dices sin adornos y sin bajar la vista. Hay un silencio seco. Algunos discípulos se miran; Wang entrecierra los ojos, reconociendo algo que preferiría no ver.','«Honesto —dice por fin el Anciano Mo—. El poder es un camino. Que no te devore a mitad de viaje.»'],c:[{x:'Esperar el veredicto',to:'veredicto'}]},
 veredicto:{h:'El veredicto',cp:1,t:['Los tres ancianos deliberan en voz baja. Después, uno a uno, anuncian los nombres. Lian es admitida y se inclina con una sonrisa que no sabía que tenía. Gordo Tao, por pura casualidad, también, y llora sobre una manga llena de dulces.','Wang aprieta los puños. «¡Es un error! ¡Un error!» Nadie le escucha.','«Y finalmente —dice el Anciano Mo— el aspirante que olvidó su apellido y recordó su razón. Bienvenido, Discípulo Común del Dragón Azur.»','El Abuelo Pei, con la voz rota, susurra solo para ti: «Hace cuarenta años yo oí mi nombre en esta misma sala, muchacho. No lo digas a nadie, pero estoy a punto de llorar.»'],
  fx:{rango:1,oro:100,xp:40},c:[{x:'Subir al tejado esa noche, junto al Abuelo Pei',to:'gancho',req:{fl:'invFin'},oc:1},{x:'Salir a respirar el aire de la noche',to:'gancho_simple',req:{no:'invFin'},oc:1}]},
 gancho:{h:'Sobre el tejado',t:['La noche es clara. A lo lejos, el Pico del Dragón se recorta contra las estrellas como un animal dormido. El Abuelo Pei, apoyado en tu cinto, habla por fin sin bromas.','«Me llamo Pei Longyin. Y no fui el último Líder Supremo de esta secta, chico. Fui el que dejó dormido al Dragón.»','«No es un símbolo. Duerme bajo esta montaña. Y esas hierbas que desaparecen… no las venden. Son su comida. Alguien está despertándolo.»','Bajo vuestros pies, el suelo tiembla una sola vez. En el acantilado norte, una luz verde parpadea entre la niebla, como un ojo que acaba de abrirse.'],c:[{x:'Mirar en silencio hasta que la luz se apague',to:'fin1'}]},
 gancho_simple:{h:'Sobre el tejado',t:['La noche es clara. En el acantilado norte, una luz verde parpadea entre la niebla. El Abuelo Pei, con la voz más baja que le has oído, murmura: «Algo se mueve debajo de esta montaña, muchacho. Y esta secta no sabe lo que guarda.»','No bromea. Esa es, quizá, la parte más inquietante.'],c:[{x:'Quedarte mirando la luz hasta que se apague',to:'fin1'}]},
 fin1:{h:'Fin del Capítulo 1 · El Reclutamiento',t:['Entraste en el Dragón Azur con una espada de bambú, una grieta en el techo y ninguna certeza. Ahora tienes amigos de tono dudoso, un rival con pelo caro, una técnica que se rasca y un secreto del tamaño de una montaña.','El verano llegará pronto. Los hornos estarán encendidos, las deudas, también, y los rencores, sin apagar.','Próximamente: Capítulo 2 — «Hornos y Rencores».'],end:'Capítulo 1 completado'}
}});
